### ISSUE TITLE
S2 - As a user I have a footer available

### ISSUE THREAD

**Issue by veljzs** [4GeeksAcademy/ecomerce-toolkit#36]
- [ ] The client should be able to go back to home from the footer
- [ ] The client should be able to go to  our social media from the footer (follow us)
- [ ] The client should be able to go to specific categories from the footer

**Comment by veljzs** [comment]
- [ ] The client should be able to go back to home from the footer
- [ ] The client should be able to go to  our social media from the footer (follow us)
- [ ] The client should be able to go to specific categories from the footer

**Comment by RoAlfonsin** [comment]
This issue was fixed in other branch
